// Mocks generated by Mockito 5.2.0 from annotations
// in ditonton/test/presentation/pages/tvseries_detail_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i11;
import 'dart:ui' as _i12;

import 'package:ditonton/common/state_enum.dart' as _i9;
import 'package:ditonton/domain/entities/tvseries.dart' as _i10;
import 'package:ditonton/domain/entities/tvseries_detail.dart' as _i7;
import 'package:ditonton/domain/usecases/get_tvseries_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/get_tvseries_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/get_watchlist_tvseries_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/remove_watchlist_tvseries.dart' as _i6;
import 'package:ditonton/domain/usecases/save_watchlist_tvseries.dart' as _i5;
import 'package:ditonton/presentation/provider/tvseries_detail_notifier.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTVSeriesDetail_0 extends _i1.Fake
    implements _i2.GetTVSeriesDetail {}

class _FakeGetTVSeriesRecommendations_1 extends _i1.Fake
    implements _i3.GetTVSeriesRecommendations {}

class _FakeGetWatchlistTVSeriesStatus_2 extends _i1.Fake
    implements _i4.GetWatchlistTVSeriesStatus {}

class _FakeSaveWatchlistTVSeries_3 extends _i1.Fake
    implements _i5.SaveWatchlistTVSeries {}

class _FakeRemoveWatchlistTVSeries_4 extends _i1.Fake
    implements _i6.RemoveWatchlistTVSeries {}

class _FakeTVSeriesDetail_5 extends _i1.Fake implements _i7.TVSeriesDetail {}

/// A class which mocks [TVSeriesDetailNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTVSeriesDetailNotifier extends _i1.Mock
    implements _i8.TVSeriesDetailNotifier {
  MockTVSeriesDetailNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTVSeriesDetail get getTVSeriesDetail =>
      (super.noSuchMethod(Invocation.getter(#getTVSeriesDetail),
          returnValue: _FakeGetTVSeriesDetail_0()) as _i2.GetTVSeriesDetail);
  @override
  _i3.GetTVSeriesRecommendations get getTVSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#getTVSeriesRecommendations),
              returnValue: _FakeGetTVSeriesRecommendations_1())
          as _i3.GetTVSeriesRecommendations);
  @override
  _i4.GetWatchlistTVSeriesStatus get getWatchListStatus =>
      (super.noSuchMethod(Invocation.getter(#getWatchListStatus),
              returnValue: _FakeGetWatchlistTVSeriesStatus_2())
          as _i4.GetWatchlistTVSeriesStatus);
  @override
  _i5.SaveWatchlistTVSeries get saveWatchlist =>
      (super.noSuchMethod(Invocation.getter(#saveWatchlist),
              returnValue: _FakeSaveWatchlistTVSeries_3())
          as _i5.SaveWatchlistTVSeries);
  @override
  _i6.RemoveWatchlistTVSeries get removeWatchlist =>
      (super.noSuchMethod(Invocation.getter(#removeWatchlist),
              returnValue: _FakeRemoveWatchlistTVSeries_4())
          as _i6.RemoveWatchlistTVSeries);
  @override
  _i7.TVSeriesDetail get tvSeries =>
      (super.noSuchMethod(Invocation.getter(#tvSeries),
          returnValue: _FakeTVSeriesDetail_5()) as _i7.TVSeriesDetail);
  @override
  _i9.RequestState get tvSeriesState =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  List<_i10.TVSeries> get tvSeriesRecommendations =>
      (super.noSuchMethod(Invocation.getter(#tvSeriesRecommendations),
          returnValue: <_i10.TVSeries>[]) as List<_i10.TVSeries>);
  @override
  _i9.RequestState get recommendationState =>
      (super.noSuchMethod(Invocation.getter(#recommendationState),
          returnValue: _i9.RequestState.Empty) as _i9.RequestState);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get isAddedToWatchlist =>
      (super.noSuchMethod(Invocation.getter(#isAddedToWatchlist),
          returnValue: false) as bool);
  @override
  String get watchlistMessage =>
      (super.noSuchMethod(Invocation.getter(#watchlistMessage), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i11.Future<void> fetchTVSeriesDetail(int? id) => (super.noSuchMethod(
      Invocation.method(#fetchTVSeriesDetail, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  _i11.Future<void> addWatchlist(_i7.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#addWatchlist, [tvSeries]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> removeFromWatchlist(_i7.TVSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeFromWatchlist, [tvSeries]),
              returnValue: Future<void>.value(),
              returnValueForMissingStub: Future<void>.value())
          as _i11.Future<void>);
  @override
  _i11.Future<void> loadWatchlistStatus(int? id) => (super.noSuchMethod(
      Invocation.method(#loadWatchlistStatus, [id]),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i11.Future<void>);
  @override
  void addListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i12.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
